import './globals.css'
import Script from 'next/script'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport = {
  viewportFit: 'cover',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Script id="browser-flag" strategy="beforeInteractive">{`
          (function () {
            var ua = navigator.userAgent;
            var safari = /Safari/i.test(ua) && !/Chrome|CriOS|Chromium|FxiOS|EdgiOS|OPiOS|Android/i.test(ua);
            document.documentElement.setAttribute('data-browser', safari ? 'safari' : 'chrome');
          })();
        `}</Script>
        {children}
      </body>
    </html>
  )
}
